redis:
  master:
    host: ${REDIS_MASTER_HOST}
  slave:
    host: ${REDIS_SLAVE_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  application:
    name: auth-service
  jwt:
    secret: ${JWT_SECRET}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${REST_APIKEY}
            redirect-uri: ${OAUTH2_BASEURL}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: none
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_BASEURL}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - name
              - email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_BASEURL}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-name: Google
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # default_batch_fetch_size: 15
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: ${CONTEXT_PATH}

# ex. https://www.dealivery.com
domain: ${DOMAIN}

custom:
  kafka-url: ${KAFKA_URL}
